### ISSUE TITLE
Formatting problem on the "Working with Optionals" wiki page

### ISSUE THREAD

**Issue by kdaniel2410** [Javacord/javacord.github.io#16]
![image](https://user-images.githubusercontent.com/18488621/104852480-29695c00-58f3-11eb-81db-614ae3d19a14.png)
Looks like the formatting hasn't worked quit so well here.

**Comment by kdaniel2410** [comment]
This is found at the bottom of [this](https://github.com/Javacord/javacord.github.io/blob/master/_wiki/essential-knowledge/working-with-optionals.md) page after expanding the "Solution"

**Comment by Bastian** [comment]
This is just the code for our old website.
The new repository for the Javacord website can be found at https://github.com/Javacord/Website

However, instead of browsing through the markdown files directly, you should visit the rendered website: https://javacord.org/wiki/essential-knowledge/optionals.html

**Comment by kdaniel2410** [comment]
Ah thank you for pointing me in the right direction
